### ISSUE TITLE
4G/LTE Shield for Rapsberry Pi - Drivers not working

### ISSUE THREAD

**Issue by samucs** [sixfab/rpiShields#1]
Hello,

This week I received my 4G/LTE Sixfab shield plus the Quectel module EC25-A. After installing Raspbian on a fresh SD Card, I followed the instructions from Tutorial 1 to copy and paste the drivers files to the Kernel folder. In my case these were the destination folders:

`/lib/modules/4.4.34-v7+/kernel/drivers/usb/serial` 
`/lib/modules/4.4.34-v7+/kernel/drivers/net/usb` 

After reboot and a dmesg command:

`[   76.669490] usb 1-1.5: new full-speed USB device number 9 using dwc_otg`
`[   76.889513] usb 1-1.5: new high-speed USB device number 10 using dwc_otg`
`[   76.999543] usb 1-1.5: New USB device found, idVendor=2c7c, idProduct=0125`
`[   76.999563] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=0`
`[   76.999577] usb 1-1.5: Product: Android`
`[   76.999602] usb 1-1.5: Manufacturer: Android`

So, there is no Quectel recognized, instead it shows up as an **Android** product. Now I am stuck since I have no idea on how to resolve this issue. Hope you guys have an answer. 

For the record, I tried to plug the board on my Windows 10 PC. The drivers were installed and I was able to connect to the module by using the QNavigator 1.4 software from Quectel. It connected and identified the module and also displayed the SIM card information (T-Modile Hologram). On PPP option I was able to set the APN to HOLOGRAM and send a message. Seems to be working fine. 

But it's definitely not working for Raspberry Pi as of today. And quectel.com is down...

Regards.

**Comment by saucompeng** [comment]
@samucs So Sorry, we have shared files with you that were not accidentally compiled. In a short time, we will fix it.

**Comment by saucompeng** [comment]
@samucs Please, update your Raspberry Pi's kernel with `sudo rpi-update` command and reboot. Then you can use /dev/ttyUSB3 dev.

**Comment by samucs** [comment]
@saucompeng It works! Thanks for your help. I am writing this message from my Rapsberry Pi connected to Sixfab 4G/LTE :)

**Comment by RajeshBhandari** [comment]
Hi , I am in a similar situation here.
I created a custom build for RaspberryPi3 via buildroot.
The kernel is at 4.9.59-v7.
I have also enabled qmi_wwan drivers in the kernel config.
In addition, I have added a /etc/systemd/network/wwan.network  file which has the following contents
```
[Match]
Name=wwan*

[Network]
DHCP=ipv4
```
On booting I get the logs
```
[   16.755177] usb 1-1.2: new high-speed USB device number 5 using dwc_otg
[   16.895303] usb 1-1.2: New USB device found, idVendor=2c7c, idProduct=0125
[   16.895494] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   16.895674] usb 1-1.2: Product: Android
[   16.895776] usb 1-1.2: Manufacturer: Android
[   16.938038] usbcore: registered new interface driver cdc_wdm
[   16.948407] qmi_wwan 1-1.2:1.4: cdc-wdm0: USB WDM device
[   16.951180] qmi_wwan 1-1.2:1.4 wwan0: register 'qmi_wwan' at usb-3f980000.usb-1.2, WWAN/QMI device, 2e:5a:02:25:1a:9e
[   16.951665] usbcore: registered new interface driver qmi_wwan

```
The wwan0 is up but it doesn't have an IP.

Am I missing something here ?
