### ISSUE TITLE
Network Priority ETH0 -> WLAN0 -> PPP0 how can do I this?

### ISSUE THREAD

**Issue by Uniphix** [sixfab/rpiShields#11]
I am curious how I can do this?   I cannot seem to get a straight answer, right now ppp0 is always higher priority over WIFI, and I want to make it so that ppp0 is in last place after ETH0 then WLAN0.

**Comment by saeedjohar** [comment]
You will need to use Route. 
https://www.systutorials.com/docs/linux/man/8-route/
