### ISSUE TITLE
Error following Tutorial 2 (ppp gprs connection)

### ISSUE THREAD

**Issue by miguelagfreitas** [sixfab/rpiShields#2]
After following all the instructions on the tutorial, whenever I try to pppd gprs call, the script prints ‘^@’ over and over again and 30 seconds later I get “warning: alarm synchronization problem”. I could not find anything relevant on the internet. Is there anyone here that can help me?

> alarm
>warning: alarm synchronization problem
>Failed
>Script chat -s -v -f /etc/chatscripts/quectel-chat-connect -T HOLOGRAM finished (pid 1441), status = 0x3
>Connect script failed

**Comment by mboyar** [comment]
I've got the same error and try to push power reset for a while, 2 secs
or from the command line:
```sh
gpio -g 25 mode out && gpio -g 25 write 1 && sleep 2 && gpio -g 25 write 0

```
now, it should be run stable.
