### ISSUE TITLE
Schematic & BOM for 3G/4G/LTE shield

### ISSUE THREAD

**Issue by ethicstechOSS** [sixfab/rpiShields#3]
Can you confirm the schematic for the 3G/4G/LTE RPI Shield uploaded in this repository is finalized and working without any issues?. Also share the BOM  if possible.

**Comment by selengalp** [comment]
Hello. The schematic file is up-to-date. Unfortunately, we can't share BOM details. But, if you need any customized design, you could mail us with your project details.
