### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by tamert** [sixfab/rpiShields#4]
Soru şu:

connect olduğunda bağlantıya nasıl restart diyebiliriz.. yeni bir ip için ?

**Comment by saucompeng** [comment]
Merhaba;

sudo ifdown ppp0
sudo ifup ppp0

**Comment by tamert** [comment]
teşekküler fakat bazı fix hataları arada bir veriyor
`
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
alarm
warning: alarm synchronization problem
Failed
Script chat -s -v -f /etc/chatscripts/quectel-chat-connect -T INTERNET finished (pid 2469), status = 0x3

Connect script failed
`

**Comment by tamert** [comment]
sanırım en kötüsü bağlantının nedensiz yere gittikten sonra tekrar bağlanmaya çalıştıramam :) saat gecenin 2 si ve sadece bir alaylı pythoncuyum :(

**Comment by tamert** [comment]
tam çalıştırdığımda kapanıyor .. pi 3 kullanıyorum acaba pinleri mi farklı oldu gibi saçma fikirler dolanıyor aklımda

**Comment by tamert** [comment]
defalarca adım adım ekleyip kurdum ama maalesef benim için büyük 200 TL başkaları için küçük bir masraf ! elveda gprs kartı

**Comment by tamert** [comment]
sanırım sorunu buldum ... pinler düzgün oturmuyormuş .. şimdi bağlandı ama 

ifdown ppp0 komudunu yazınca 
unkown interface diyor

**Comment by tamert** [comment]
try :  sudo ifconfig ppp0 down 
yes work ! 
but it not reopen connection 
so try later :  sudo ifconfig eth0 up

**Comment by tamert** [comment]
şimdilik manuel bir yöntem denedim.

yani gpio ile kapatıp açıp connect yapma gibi .. evet bana da çok ilkel geldi ama çalışıyor 
ifdown ve ifup için bir config lazım ancak tekrardan raspbian'ı göçertmekten korkuyorum

**Comment by tamert** [comment]
3. gün 
ben hala sağlıklı bir gprs bağlantısı kuramadım.. yani gün içinde bağlı oldu ama tekrar açtığımda yine 

**NO DIALTONE**  diyip **disconnect script failed** hatası verdi...

Ankara'da Konya sokağa uğradım Raspberry ile GPRS arasına bir kablo bulayım diye ama bulamadım  sanırım ara kablosunu yine robotistan'dan alacağım...

Şu fix hatayı nası çözerim diye Hz. Google'a sordum ve vardığım bir noktada bu... 
https://www.linuxquestions.org/questions/slackware-14/pppd-doesn%27t-run-ip-down-on-disconnect-160762/
forumda Ethyriel kendince bir şeyler denemiş ama başaramamış...  "Wow, an operating system that makes sense! Be gone Microsoft!" demiş anladığım kadarıyla :D 
neyse.. tek istediğim rasbian açılınca otomatikman bağlanmaya çalışsın ve ben istediğmde bağlantıyı reflesh'lesin bu kadar zor mu ? 

Yeni siparişler verebilmem için bu şarttı.. ama malesef çözümleyemedim..

**Comment by saucompeng** [comment]
Merhaba tamert, mesai saati icerisinde sorularini yanitlamaya calisacagim. Bu problemlerin urunumuzle bir alakasi yok, linux ile alakali.

**Comment by saucompeng** [comment]
Merhabalar;

Öncelikle /etc/network/interfaces dosyasına aşağıdaki satırları ekleyiniz.

```
iface ppp0 inet ppp
provider gprs
```


Daha sonrasında aşağıdaki şekilde bir script yazıp bunu raspberry pi içerisinde bir servis içerisinde koşturmanız gerekiyor. Servis yazma konusunda bu linki takip edebilirsiniz. https://forum.raspi-tr.com/thread-1266.html


```
#!/bin/sh

echo "start"
NCHECK = 'ifconfig ppp'
NCHECK1 = 'echo $NCHECK | cut -d " " -f '

while true; do
	if [ "$NCHECK" = "PPP0" ]; then
		echo "Connectin up, reconnect not required"
	else
		echo "Connection down, reconnecting..."
		/sbin/ifup ppp0
	fi
done
```

**Comment by tamert** [comment]
interface'e ekledim fakat not configured diyor şimdide :)

**Comment by tamert** [comment]
sudo ifup ppp0 yazınca 

pppd call gprs komudunu işliyor..

**Comment by tamert** [comment]
bağlantı düşünce led'in sönmesi kafamı karıştırıyor... led yanmayınca klasik **alarm** hatasını veriyor

**Comment by tamert** [comment]
şöyle anlatayım.. ifdown oluyor sürekli .. ve ifdown olunca led sönüyor led sönünce de alarm hatası veriyor.. sonuç sonsuz döngü
