### ISSUE TITLE
Issue during tutorial 3.

### ISSUE THREAD

**Issue by benkawecki** [sixfab/rpiShields#8]
Hello,

I'm currently working on establishing a 4g connection following tutorial 3, but failing at the <code> sudo pppd call gprs</code> stage. I am currently using an existing Verizon Micro SIM card on my plan and have contacted Verizon to have them associate this modem with my plan. They said that they see a connection on their end. Below is a copy of my terminal read out. I have been going through forums for the past couple days but haven't seen a concrete solution to this issue. Thanks in advanced for any help you can provide. 

pi@raspberrypi:~ $ sudo pppd call gprs
pppd options in effect:
debug           # (from /etc/ppp/peers/gprs)
nodetach                # (from /etc/ppp/peers/gprs)
dump            # (from /etc/ppp/peers/gprs)
noauth          # (from /etc/ppp/peers/gprs)
remotename 3gppp                # (from /etc/ppp/peers/gprs)
/dev/ttyUSB3            # (from /etc/ppp/peers/gprs)
115200          # (from /etc/ppp/peers/gprs)
lock            # (from /etc/ppp/peers/gprs)
connect chat -s -v -f /etc/chatscripts/quectel-chat-connect -T internet        # (from /etc/ppp/peers/gprs)
disconnect chat -s -v -f /etc/chatscripts/quectel-chat-disconnect              # (from /etc/ppp/peers/gprs)
nocrtscts               # (from /etc/ppp/peers/gprs)
modem           # (from /etc/ppp/peers/gprs)
asyncmap 0              # (from /etc/ppp/options)
lcp-echo-failure 4              # (from /etc/ppp/options)
lcp-echo-interval 30            # (from /etc/ppp/options)
hide-password           # (from /etc/ppp/peers/gprs)
novj            # (from /etc/ppp/peers/gprs)
novjccomp               # (from /etc/ppp/peers/gprs)
ipcp-accept-local               # (from /etc/ppp/peers/gprs)
ipcp-accept-remote              # (from /etc/ppp/peers/gprs)
ipparam 3gppp           # (from /etc/ppp/peers/gprs)
noipdefault             # (from /etc/ppp/peers/gprs)
ipcp-max-failure 30             # (from /etc/ppp/peers/gprs)
defaultroute            # (from /etc/ppp/peers/gprs)
usepeerdns              # (from /etc/ppp/peers/gprs)
noccp           # (from /etc/ppp/peers/gprs)
noipx           # (from /etc/ppp/options)
abort on (BUSY)
abort on (NO CARRIER)
abort on (NO DIALTONE)
abort on (ERROR)
abort on (NO ANSWER)
timeout set to 30 seconds
send (AT^M)
expect (OK)
^M
OK
 -- got it

send (ATE0^M)
expect (OK)
^M
^M
OK
 -- got it

send (ATI;+CSUB;+CSQ;+COPS?;+CGREG?;&D2^M)
expect (OK)
^M
^M
Quectel^M
EC25^M
Revision: EC25VFAR02A11M4G^M
^M
SubEdition: V06^M
^M
+CSQ: 23,99^M
^M
+COPS: 0,0,"Verizon Wireless",7^M
^M
+CGREG: 0,1^M
^M
OK
 -- got it

send (AT+CGDCONT=1,"IP","internet",,0,0^M)
expect (OK)
^M
^M
OK
 -- got it

send (ATD*99#^M)
expect (CONNECT)
^M
^M
CONNECT
 -- got it

Script chat -s -v -f /etc/chatscripts/quectel-chat-connect -T internet finished (pid 1507), status = 0x0
Serial connection established.
using channel 4
Using interface ppp0
Connect: ppp0 <--> /dev/ttyUSB3
sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0xfe2902cc> <pcomp> <accomp>]
rcvd [LCP ConfReq id=0x9 <asyncmap 0x0> <auth chap MD5> <magic 0xa853c4c7> <pcomp> <accomp>]
No auth is possible
sent [LCP ConfRej id=0x9 <auth chap MD5>]
rcvd [LCP ConfAck id=0x1 <asyncmap 0x0> <magic 0xfe2902cc> <pcomp> <accomp>]
rcvd [LCP ConfReq id=0xa <asyncmap 0x0> <magic 0xa853c4c7> <pcomp> <accomp>]
sent [LCP ConfAck id=0xa <asyncmap 0x0> <magic 0xa853c4c7> <pcomp> <accomp>]
sent [LCP EchoReq id=0x0 magic=0xfe2902cc]
sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
rcvd [LCP DiscReq id=0xb magic=0xa853c4c7]
rcvd [LCP EchoRep id=0x0 magic=0xa853c4c7 fe 29 02 cc]
Modem hangup
Connection terminated.

**Comment by saeedjohar** [comment]
Hi, 
Since you are using verizon carrier. So the APN should be vzwinternet instead of internet, that is, 
The command will be as follows:
`sudo ./ppp-creator.sh vzwinternet ttyUSB3`

**Comment by benkawecki** [comment]
This seems to have fixed the problem, Thanks for the help!
